-- Dados iniciais. Pode rodar várias vezes: ON CONFLICT evita duplicidade.
insert into public.characters(theme,name) values
  ('ESPORTE','Lionel Messi'),
  ('ESPORTE','Cristiano Ronaldo'),
  ('ESPORTE','Neymar'),
  ('ESPORTE','Michael Jordan'),
  ('ESPORTE','LeBron James'),
  ('ESPORTE','Ayrton Senna'),
  ('ESPORTE','Lewis Hamilton'),
  ('ESPORTE','Usain Bolt'),
  ('ESPORTE','Pelé'),
  ('ESPORTE','Ronaldo Fenômeno'),
  ('ESPORTE','Ronaldinho Gaúcho'),
  ('ESPORTE','Galvão Bueno'),
  ('ESPORTE','Marta'),
  ('ESPORTE','Vinícius Júnior'),
  ('ESPORTE','Kylian Mbappé'),
  ('ESPORTE','Novak Djokovic'),
  ('ESPORTE','Rafael Nadal'),
  ('ESPORTE','Roger Federer'),
  ('ESPORTE','Serena Williams'),
  ('ESPORTE','Simone Biles'),
  ('ESPORTE','Max Verstappen'),
  ('ESPORTE','Gabriel Medina'),
  ('ESPORTE','Rebeca Andrade'),
  ('ESPORTE','Gustavo Kuerten'),
  ('ESPORTE','Oscar Schmidt'),
  ('ESPORTE','Anderson Silva'),
  ('ESPORTE','José Aldo'),
  ('ESPORTE','Mike Tyson'),
  ('ESPORTE','Muhammad Ali'),
  ('ESPORTE','Tom Brady'),
  ('ESPORTE','Stephen Curry'),
  ('ESPORTE','Kobe Bryant'),
  ('ESPORTE','Shaquille O’Neal'),
  ('ESPORTE','Magic Johnson'),
  ('ESPORTE','Larry Bird'),
  ('ESPORTE','Giannis Antetokounmpo'),
  ('ESPORTE','Luka Dončić'),
  ('ESPORTE','Kevin Durant'),
  ('ESPORTE','Tiger Woods'),
  ('ESPORTE','Michael Phelps')
on conflict(theme,name) do nothing;

insert into public.characters(theme,name) values
  ('FILMES','Harry Potter'),
  ('FILMES','Homem-Aranha'),
  ('FILMES','Batman'),
  ('FILMES','Superman'),
  ('FILMES','Homem de Ferro'),
  ('FILMES','Jack Sparrow'),
  ('FILMES','Rocky Balboa'),
  ('FILMES','Darth Vader'),
  ('FILMES','Hulk'),
  ('FILMES','Thanos'),
  ('FILMES','Capitão América'),
  ('FILMES','Thor'),
  ('FILMES','Viúva Negra'),
  ('FILMES','Pantera Negra'),
  ('FILMES','Wolverine'),
  ('FILMES','Deadpool'),
  ('FILMES','Indiana Jones'),
  ('FILMES','Forrest Gump'),
  ('FILMES','Neo'),
  ('FILMES','John Wick'),
  ('FILMES','Shrek'),
  ('FILMES','Elsa'),
  ('FILMES','Woody'),
  ('FILMES','Buzz Lightyear'),
  ('FILMES','Simba'),
  ('FILMES','Aladdin'),
  ('FILMES','Mulan'),
  ('FILMES','Moana'),
  ('FILMES','Marty McFly'),
  ('FILMES','ET')
on conflict(theme,name) do nothing;

insert into public.characters(theme,name) values
  ('GAMES','Mario'),
  ('GAMES','Luigi'),
  ('GAMES','Sonic'),
  ('GAMES','Link'),
  ('GAMES','Zelda'),
  ('GAMES','Kratos'),
  ('GAMES','Master Chief'),
  ('GAMES','Lara Croft'),
  ('GAMES','Pac-Man'),
  ('GAMES','Pikachu'),
  ('GAMES','Donkey Kong'),
  ('GAMES','Kirby'),
  ('GAMES','Crash Bandicoot'),
  ('GAMES','Spyro'),
  ('GAMES','Samus Aran'),
  ('GAMES','Mega Man'),
  ('GAMES','Ryu'),
  ('GAMES','Ken Masters'),
  ('GAMES','Sub-Zero'),
  ('GAMES','Scorpion'),
  ('GAMES','Chun-Li'),
  ('GAMES','Cloud Strife'),
  ('GAMES','Sephiroth'),
  ('GAMES','Steve Minecraft'),
  ('GAMES','Creeper'),
  ('GAMES','Geralt de Rívia'),
  ('GAMES','Ezio Auditore'),
  ('GAMES','Nathan Drake'),
  ('GAMES','Joel Miller'),
  ('GAMES','Ellie Williams')
on conflict(theme,name) do nothing;

insert into public.characters(theme,name) values
  ('ANIMAIS','Cachorro'),
  ('ANIMAIS','Gato'),
  ('ANIMAIS','Leão'),
  ('ANIMAIS','Tigre'),
  ('ANIMAIS','Elefante'),
  ('ANIMAIS','Girafa'),
  ('ANIMAIS','Zebra'),
  ('ANIMAIS','Macaco'),
  ('ANIMAIS','Gorila'),
  ('ANIMAIS','Chimpanzé'),
  ('ANIMAIS','Urso-pardo'),
  ('ANIMAIS','Urso-polar'),
  ('ANIMAIS','Panda'),
  ('ANIMAIS','Lobo'),
  ('ANIMAIS','Raposa'),
  ('ANIMAIS','Hiena'),
  ('ANIMAIS','Rinoceronte'),
  ('ANIMAIS','Hipopótamo'),
  ('ANIMAIS','Cavalo'),
  ('ANIMAIS','Burro'),
  ('ANIMAIS','Jumento'),
  ('ANIMAIS','Vaca'),
  ('ANIMAIS','Touro'),
  ('ANIMAIS','Búfalo'),
  ('ANIMAIS','Bode'),
  ('ANIMAIS','Cabra'),
  ('ANIMAIS','Ovelha'),
  ('ANIMAIS','Porco'),
  ('ANIMAIS','Coelho'),
  ('ANIMAIS','Lebre'),
  ('ANIMAIS','Rato'),
  ('ANIMAIS','Hamster'),
  ('ANIMAIS','Esquilo'),
  ('ANIMAIS','Capivara'),
  ('ANIMAIS','Tamanduá'),
  ('ANIMAIS','Tatu'),
  ('ANIMAIS','Preguiça'),
  ('ANIMAIS','Canguru'),
  ('ANIMAIS','Coala'),
  ('ANIMAIS','Ornitorrinco'),
  ('ANIMAIS','Golfinho'),
  ('ANIMAIS','Baleia'),
  ('ANIMAIS','Orca'),
  ('ANIMAIS','Tubarão'),
  ('ANIMAIS','Arraia'),
  ('ANIMAIS','Polvo'),
  ('ANIMAIS','Lula'),
  ('ANIMAIS','Caranguejo'),
  ('ANIMAIS','Lagosta'),
  ('ANIMAIS','Camarão'),
  ('ANIMAIS','Pinguim'),
  ('ANIMAIS','Avestruz'),
  ('ANIMAIS','Águia'),
  ('ANIMAIS','Falcão'),
  ('ANIMAIS','Coruja'),
  ('ANIMAIS','Papagaio'),
  ('ANIMAIS','Arara'),
  ('ANIMAIS','Tucano'),
  ('ANIMAIS','Pombo'),
  ('ANIMAIS','Galinha'),
  ('ANIMAIS','Galo'),
  ('ANIMAIS','Pato'),
  ('ANIMAIS','Ganso'),
  ('ANIMAIS','Cisne'),
  ('ANIMAIS','Flamingo'),
  ('ANIMAIS','Pavão'),
  ('ANIMAIS','Beija-flor'),
  ('ANIMAIS','Pica-pau'),
  ('ANIMAIS','Canário'),
  ('ANIMAIS','Sabiá'),
  ('ANIMAIS','Jacaré'),
  ('ANIMAIS','Crocodilo'),
  ('ANIMAIS','Iguana'),
  ('ANIMAIS','Camaleão'),
  ('ANIMAIS','Lagarto'),
  ('ANIMAIS','Cobra'),
  ('ANIMAIS','Jiboia'),
  ('ANIMAIS','Sucuri'),
  ('ANIMAIS','Cascavel'),
  ('ANIMAIS','Tartaruga'),
  ('ANIMAIS','Jabuti'),
  ('ANIMAIS','Sapo'),
  ('ANIMAIS','Rã'),
  ('ANIMAIS','Salamandra'),
  ('ANIMAIS','Borboleta'),
  ('ANIMAIS','Abelha'),
  ('ANIMAIS','Formiga'),
  ('ANIMAIS','Mosquito'),
  ('ANIMAIS','Besouro'),
  ('ANIMAIS','Joaninha'),
  ('ANIMAIS','Libélula'),
  ('ANIMAIS','Gafanhoto'),
  ('ANIMAIS','Grilo'),
  ('ANIMAIS','Aranha'),
  ('ANIMAIS','Escorpião'),
  ('ANIMAIS','Minhoca'),
  ('ANIMAIS','Caracol'),
  ('ANIMAIS','Lesma'),
  ('ANIMAIS','Estrela-do-mar'),
  ('ANIMAIS','Cavalo-marinho')
on conflict(theme,name) do nothing;

insert into public.characters(theme,name) values
  ('PAÍSES','Brasil'),
  ('PAÍSES','Argentina'),
  ('PAÍSES','Uruguai'),
  ('PAÍSES','Paraguai'),
  ('PAÍSES','Chile'),
  ('PAÍSES','Peru'),
  ('PAÍSES','Bolívia'),
  ('PAÍSES','Colômbia'),
  ('PAÍSES','Venezuela'),
  ('PAÍSES','Equador'),
  ('PAÍSES','México'),
  ('PAÍSES','Canadá'),
  ('PAÍSES','Estados Unidos'),
  ('PAÍSES','Portugal'),
  ('PAÍSES','Espanha'),
  ('PAÍSES','França'),
  ('PAÍSES','Alemanha'),
  ('PAÍSES','Itália'),
  ('PAÍSES','Reino Unido'),
  ('PAÍSES','Irlanda'),
  ('PAÍSES','Países Baixos'),
  ('PAÍSES','Bélgica'),
  ('PAÍSES','Suíça'),
  ('PAÍSES','Áustria'),
  ('PAÍSES','Polônia'),
  ('PAÍSES','República Tcheca'),
  ('PAÍSES','Eslováquia'),
  ('PAÍSES','Hungria'),
  ('PAÍSES','Romênia'),
  ('PAÍSES','Bulgária'),
  ('PAÍSES','Grécia'),
  ('PAÍSES','Croácia'),
  ('PAÍSES','Sérvia'),
  ('PAÍSES','Eslovênia'),
  ('PAÍSES','Bósnia e Herzegovina'),
  ('PAÍSES','Albânia'),
  ('PAÍSES','Macedônia do Norte'),
  ('PAÍSES','Noruega'),
  ('PAÍSES','Suécia'),
  ('PAÍSES','Finlândia'),
  ('PAÍSES','Dinamarca'),
  ('PAÍSES','Islândia'),
  ('PAÍSES','Estônia'),
  ('PAÍSES','Letônia'),
  ('PAÍSES','Lituânia'),
  ('PAÍSES','Ucrânia'),
  ('PAÍSES','Moldávia'),
  ('PAÍSES','Geórgia'),
  ('PAÍSES','Armênia'),
  ('PAÍSES','Azerbaijão'),
  ('PAÍSES','Turquia'),
  ('PAÍSES','Rússia'),
  ('PAÍSES','China'),
  ('PAÍSES','Japão'),
  ('PAÍSES','Coreia do Sul'),
  ('PAÍSES','Coreia do Norte'),
  ('PAÍSES','Índia'),
  ('PAÍSES','Paquistão'),
  ('PAÍSES','Bangladesh'),
  ('PAÍSES','Nepal'),
  ('PAÍSES','Butão'),
  ('PAÍSES','Sri Lanka'),
  ('PAÍSES','Maldivas'),
  ('PAÍSES','Tailândia'),
  ('PAÍSES','Vietnã'),
  ('PAÍSES','Laos'),
  ('PAÍSES','Camboja'),
  ('PAÍSES','Malásia'),
  ('PAÍSES','Singapura'),
  ('PAÍSES','Indonésia'),
  ('PAÍSES','Filipinas'),
  ('PAÍSES','Mongólia'),
  ('PAÍSES','Cazaquistão'),
  ('PAÍSES','Uzbequistão'),
  ('PAÍSES','Israel'),
  ('PAÍSES','Jordânia'),
  ('PAÍSES','Líbano'),
  ('PAÍSES','Arábia Saudita'),
  ('PAÍSES','Emirados Árabes Unidos'),
  ('PAÍSES','Catar'),
  ('PAÍSES','Kuwait'),
  ('PAÍSES','Egito'),
  ('PAÍSES','Marrocos'),
  ('PAÍSES','Argélia'),
  ('PAÍSES','Tunísia'),
  ('PAÍSES','África do Sul'),
  ('PAÍSES','Nigéria'),
  ('PAÍSES','Gana'),
  ('PAÍSES','Quênia'),
  ('PAÍSES','Etiópia'),
  ('PAÍSES','Angola'),
  ('PAÍSES','Moçambique'),
  ('PAÍSES','Madagascar'),
  ('PAÍSES','Austrália'),
  ('PAÍSES','Nova Zelândia'),
  ('PAÍSES','Fiji'),
  ('PAÍSES','Cuba'),
  ('PAÍSES','Jamaica'),
  ('PAÍSES','Haiti'),
  ('PAÍSES','Panamá'),
  ('PAÍSES','Costa Rica')
on conflict(theme,name) do nothing;

insert into public.characters(theme,name) values
  ('PROFISSÕES','Médico'),
  ('PROFISSÕES','Enfermeiro'),
  ('PROFISSÕES','Dentista'),
  ('PROFISSÕES','Veterinário'),
  ('PROFISSÕES','Psicólogo'),
  ('PROFISSÕES','Fisioterapeuta'),
  ('PROFISSÕES','Nutricionista'),
  ('PROFISSÕES','Farmacêutico'),
  ('PROFISSÕES','Professor'),
  ('PROFISSÕES','Pedagogo'),
  ('PROFISSÕES','Advogado'),
  ('PROFISSÕES','Juiz'),
  ('PROFISSÕES','Promotor'),
  ('PROFISSÕES','Policial'),
  ('PROFISSÕES','Bombeiro'),
  ('PROFISSÕES','Militar'),
  ('PROFISSÕES','Engenheiro civil'),
  ('PROFISSÕES','Engenheiro mecânico'),
  ('PROFISSÕES','Engenheiro elétrico'),
  ('PROFISSÕES','Arquiteto'),
  ('PROFISSÕES','Designer'),
  ('PROFISSÕES','Programador'),
  ('PROFISSÕES','Analista de sistemas'),
  ('PROFISSÕES','Cientista de dados'),
  ('PROFISSÕES','Contador'),
  ('PROFISSÕES','Administrador'),
  ('PROFISSÕES','Economista'),
  ('PROFISSÕES','Bancário'),
  ('PROFISSÕES','Corretor de imóveis'),
  ('PROFISSÕES','Vendedor'),
  ('PROFISSÕES','Caixa'),
  ('PROFISSÕES','Atendente'),
  ('PROFISSÕES','Garçom'),
  ('PROFISSÕES','Cozinheiro'),
  ('PROFISSÕES','Chef de cozinha'),
  ('PROFISSÕES','Padeiro'),
  ('PROFISSÕES','Confeiteiro'),
  ('PROFISSÕES','Açougueiro'),
  ('PROFISSÕES','Motorista'),
  ('PROFISSÕES','Caminhoneiro'),
  ('PROFISSÕES','Motoboy'),
  ('PROFISSÕES','Piloto de avião'),
  ('PROFISSÕES','Comissário de bordo'),
  ('PROFISSÕES','Mecânico'),
  ('PROFISSÕES','Eletricista'),
  ('PROFISSÕES','Encanador'),
  ('PROFISSÕES','Pedreiro'),
  ('PROFISSÕES','Pintor'),
  ('PROFISSÕES','Marceneiro'),
  ('PROFISSÕES','Serralheiro'),
  ('PROFISSÕES','Soldador'),
  ('PROFISSÕES','Jardineiro'),
  ('PROFISSÕES','Agricultor'),
  ('PROFISSÕES','Pecuarista'),
  ('PROFISSÕES','Biólogo'),
  ('PROFISSÕES','Químico'),
  ('PROFISSÕES','Físico'),
  ('PROFISSÕES','Astrônomo'),
  ('PROFISSÕES','Geólogo'),
  ('PROFISSÕES','Arqueólogo'),
  ('PROFISSÕES','Jornalista'),
  ('PROFISSÕES','Fotógrafo'),
  ('PROFISSÕES','Cinegrafista'),
  ('PROFISSÕES','Editor de vídeo'),
  ('PROFISSÕES','Ator'),
  ('PROFISSÕES','Atriz'),
  ('PROFISSÕES','Cantor'),
  ('PROFISSÕES','Músico'),
  ('PROFISSÕES','Dançarino'),
  ('PROFISSÕES','DJ'),
  ('PROFISSÕES','Escritor'),
  ('PROFISSÕES','Poeta'),
  ('PROFISSÕES','Tradutor'),
  ('PROFISSÕES','Intérprete'),
  ('PROFISSÕES','Publicitário'),
  ('PROFISSÕES','Influenciador'),
  ('PROFISSÕES','Youtuber'),
  ('PROFISSÕES','Streamer'),
  ('PROFISSÕES','Jogador de futebol'),
  ('PROFISSÕES','Jogador de basquete'),
  ('PROFISSÕES','Árbitro'),
  ('PROFISSÕES','Personal trainer'),
  ('PROFISSÕES','Cabeleireiro'),
  ('PROFISSÕES','Barbeiro'),
  ('PROFISSÕES','Maquiador'),
  ('PROFISSÕES','Manicure'),
  ('PROFISSÕES','Costureiro'),
  ('PROFISSÕES','Estilista'),
  ('PROFISSÕES','Joalheiro'),
  ('PROFISSÕES','Relojoeiro'),
  ('PROFISSÕES','Carteiro'),
  ('PROFISSÕES','Bibliotecário'),
  ('PROFISSÕES','Recepcionista'),
  ('PROFISSÕES','Secretário'),
  ('PROFISSÕES','Segurança'),
  ('PROFISSÕES','Vigilante'),
  ('PROFISSÕES','Faxineiro'),
  ('PROFISSÕES','Lixeiro'),
  ('PROFISSÕES','Guia turístico'),
  ('PROFISSÕES','Cientista')
on conflict(theme,name) do nothing;

insert into public.characters(theme,name) values
  ('OBJETOS','Celular'),
  ('OBJETOS','Notebook'),
  ('OBJETOS','Computador'),
  ('OBJETOS','Televisão'),
  ('OBJETOS','Controle remoto'),
  ('OBJETOS','Fone de ouvido'),
  ('OBJETOS','Caixa de som'),
  ('OBJETOS','Relógio'),
  ('OBJETOS','Óculos'),
  ('OBJETOS','Boné'),
  ('OBJETOS','Chapéu'),
  ('OBJETOS','Camiseta'),
  ('OBJETOS','Calça'),
  ('OBJETOS','Tênis'),
  ('OBJETOS','Sapato'),
  ('OBJETOS','Chinelo'),
  ('OBJETOS','Meia'),
  ('OBJETOS','Mochila'),
  ('OBJETOS','Mala'),
  ('OBJETOS','Carteira'),
  ('OBJETOS','Chave'),
  ('OBJETOS','Cadeado'),
  ('OBJETOS','Tesoura'),
  ('OBJETOS','Faca'),
  ('OBJETOS','Garfo'),
  ('OBJETOS','Colher'),
  ('OBJETOS','Prato'),
  ('OBJETOS','Copo'),
  ('OBJETOS','Caneca'),
  ('OBJETOS','Garrafa'),
  ('OBJETOS','Panela'),
  ('OBJETOS','Frigideira'),
  ('OBJETOS','Liquidificador'),
  ('OBJETOS','Batedeira'),
  ('OBJETOS','Geladeira'),
  ('OBJETOS','Fogão'),
  ('OBJETOS','Micro-ondas'),
  ('OBJETOS','Torradeira'),
  ('OBJETOS','Cafeteira'),
  ('OBJETOS','Ventilador'),
  ('OBJETOS','Ar-condicionado'),
  ('OBJETOS','Sofá'),
  ('OBJETOS','Cadeira'),
  ('OBJETOS','Mesa'),
  ('OBJETOS','Cama'),
  ('OBJETOS','Travesseiro'),
  ('OBJETOS','Cobertor'),
  ('OBJETOS','Toalha'),
  ('OBJETOS','Espelho'),
  ('OBJETOS','Escova de dentes'),
  ('OBJETOS','Pasta de dente'),
  ('OBJETOS','Sabonete'),
  ('OBJETOS','Shampoo'),
  ('OBJETOS','Pente'),
  ('OBJETOS','Escova de cabelo'),
  ('OBJETOS','Livro'),
  ('OBJETOS','Caderno'),
  ('OBJETOS','Caneta'),
  ('OBJETOS','Lápis'),
  ('OBJETOS','Borracha'),
  ('OBJETOS','Régua'),
  ('OBJETOS','Apontador'),
  ('OBJETOS','Calculadora'),
  ('OBJETOS','Grampeador'),
  ('OBJETOS','Clipe'),
  ('OBJETOS','Papel'),
  ('OBJETOS','Envelope'),
  ('OBJETOS','Caixa'),
  ('OBJETOS','Martelo'),
  ('OBJETOS','Chave de fenda'),
  ('OBJETOS','Alicate'),
  ('OBJETOS','Furadeira'),
  ('OBJETOS','Serrote'),
  ('OBJETOS','Escada'),
  ('OBJETOS','Vassoura'),
  ('OBJETOS','Rodo'),
  ('OBJETOS','Balde'),
  ('OBJETOS','Mangueira'),
  ('OBJETOS','Guarda-chuva'),
  ('OBJETOS','Bicicleta'),
  ('OBJETOS','Patinete'),
  ('OBJETOS','Skate'),
  ('OBJETOS','Bola'),
  ('OBJETOS','Raquete'),
  ('OBJETOS','Violão'),
  ('OBJETOS','Guitarra'),
  ('OBJETOS','Piano'),
  ('OBJETOS','Microfone'),
  ('OBJETOS','Câmera'),
  ('OBJETOS','Tripé'),
  ('OBJETOS','Lanterna'),
  ('OBJETOS','Vela'),
  ('OBJETOS','Isqueiro'),
  ('OBJETOS','Brinquedo'),
  ('OBJETOS','Boneca'),
  ('OBJETOS','Quebra-cabeça'),
  ('OBJETOS','Dado'),
  ('OBJETOS','Baralho'),
  ('OBJETOS','Capacete'),
  ('OBJETOS','Extintor')
on conflict(theme,name) do nothing;

insert into public.characters(theme,name) values
  ('COMIDAS','Pizza'),
  ('COMIDAS','Hambúrguer'),
  ('COMIDAS','Cachorro-quente'),
  ('COMIDAS','Lasanha'),
  ('COMIDAS','Macarrão'),
  ('COMIDAS','Arroz'),
  ('COMIDAS','Feijão'),
  ('COMIDAS','Bife'),
  ('COMIDAS','Frango assado'),
  ('COMIDAS','Peixe'),
  ('COMIDAS','Sushi'),
  ('COMIDAS','Temaki'),
  ('COMIDAS','Pastel'),
  ('COMIDAS','Coxinha'),
  ('COMIDAS','Kibe'),
  ('COMIDAS','Esfiha'),
  ('COMIDAS','Pão de queijo'),
  ('COMIDAS','Pão francês'),
  ('COMIDAS','Tapioca'),
  ('COMIDAS','Cuscuz'),
  ('COMIDAS','Feijoada'),
  ('COMIDAS','Churrasco'),
  ('COMIDAS','Strogonoff'),
  ('COMIDAS','Risoto'),
  ('COMIDAS','Nhoque'),
  ('COMIDAS','Panqueca'),
  ('COMIDAS','Omelete'),
  ('COMIDAS','Salada'),
  ('COMIDAS','Sopa'),
  ('COMIDAS','Caldo'),
  ('COMIDAS','Batata frita'),
  ('COMIDAS','Purê de batata'),
  ('COMIDAS','Mandioca frita'),
  ('COMIDAS','Polenta'),
  ('COMIDAS','Milho cozido'),
  ('COMIDAS','Pipoca'),
  ('COMIDAS','Brigadeiro'),
  ('COMIDAS','Beijinho'),
  ('COMIDAS','Pudim'),
  ('COMIDAS','Bolo de chocolate'),
  ('COMIDAS','Bolo de cenoura'),
  ('COMIDAS','Sorvete'),
  ('COMIDAS','Açaí'),
  ('COMIDAS','Chocolate'),
  ('COMIDAS','Paçoca'),
  ('COMIDAS','Pé de moleque'),
  ('COMIDAS','Doce de leite'),
  ('COMIDAS','Goiabada'),
  ('COMIDAS','Romeu e Julieta'),
  ('COMIDAS','Mousse'),
  ('COMIDAS','Gelatina'),
  ('COMIDAS','Churros'),
  ('COMIDAS','Donut'),
  ('COMIDAS','Cookie'),
  ('COMIDAS','Brownie'),
  ('COMIDAS','Croissant'),
  ('COMIDAS','Waffle'),
  ('COMIDAS','Cereal'),
  ('COMIDAS','Iogurte'),
  ('COMIDAS','Queijo'),
  ('COMIDAS','Presunto'),
  ('COMIDAS','Salame'),
  ('COMIDAS','Ovo'),
  ('COMIDAS','Bacon'),
  ('COMIDAS','Linguiça'),
  ('COMIDAS','Salsicha'),
  ('COMIDAS','Alface'),
  ('COMIDAS','Tomate'),
  ('COMIDAS','Cenoura'),
  ('COMIDAS','Beterraba'),
  ('COMIDAS','Abóbora'),
  ('COMIDAS','Abobrinha'),
  ('COMIDAS','Berinjela'),
  ('COMIDAS','Brócolis'),
  ('COMIDAS','Couve-flor'),
  ('COMIDAS','Espinafre'),
  ('COMIDAS','Banana'),
  ('COMIDAS','Maçã'),
  ('COMIDAS','Laranja'),
  ('COMIDAS','Uva'),
  ('COMIDAS','Morango'),
  ('COMIDAS','Manga'),
  ('COMIDAS','Abacaxi'),
  ('COMIDAS','Melancia'),
  ('COMIDAS','Melão'),
  ('COMIDAS','Mamão'),
  ('COMIDAS','Pera'),
  ('COMIDAS','Pêssego'),
  ('COMIDAS','Kiwi'),
  ('COMIDAS','Limão'),
  ('COMIDAS','Coco'),
  ('COMIDAS','Maracujá'),
  ('COMIDAS','Goiaba'),
  ('COMIDAS','Ameixa'),
  ('COMIDAS','Cereja'),
  ('COMIDAS','Jabuticaba'),
  ('COMIDAS','Acerola'),
  ('COMIDAS','Castanha'),
  ('COMIDAS','Amendoim'),
  ('COMIDAS','Granola')
on conflict(theme,name) do nothing;
