-- 011: novos temas e personagens (com apelidos aceitos no palpite).
insert into public.characters(theme,name,aliases) values
 ('FUTEBOL','Lionel Messi',array['Messi']),
 ('FUTEBOL','Cristiano Ronaldo',array['CR7']),
 ('FUTEBOL','Neymar',array['Neymar Jr']),
 ('FUTEBOL','Vinícius Júnior',array['Vini Jr']),
 ('FUTEBOL','Kylian Mbappé','{}'::text[]),
 ('FUTEBOL','Erling Haaland','{}'::text[]),
 ('FUTEBOL','Pelé','{}'::text[]),
 ('FUTEBOL','Ronaldo Fenômeno',array['Ronaldo']),
 ('FUTEBOL','Ronaldinho Gaúcho',array['Ronaldinho']),
 ('FUTEBOL','Kaká','{}'::text[]),
 ('FUTEBOL','Romário','{}'::text[]),
 ('FUTEBOL','Zico','{}'::text[]),
 ('FUTEBOL','Garrincha','{}'::text[]),
 ('FUTEBOL','Rivaldo','{}'::text[]),
 ('FUTEBOL','Cafu','{}'::text[]),
 ('FUTEBOL','Roberto Carlos','{}'::text[]),
 ('FUTEBOL','Marta','{}'::text[]),
 ('FUTEBOL','Diego Maradona',array['Maradona']),
 ('FUTEBOL','Zinedine Zidane',array['Zidane']),
 ('FUTEBOL','Johan Cruyff','{}'::text[]),
 ('FUTEBOL','Franz Beckenbauer','{}'::text[]),
 ('FUTEBOL','Thierry Henry','{}'::text[]),
 ('FUTEBOL','Luka Modrić','{}'::text[]),
 ('FUTEBOL','Kevin De Bruyne','{}'::text[]),
 ('FUTEBOL','Mohamed Salah',array['Salah']),
 ('FUTEBOL','Robert Lewandowski','{}'::text[]),
 ('FUTEBOL','Harry Kane','{}'::text[]),
 ('FUTEBOL','Jude Bellingham','{}'::text[]),
 ('FUTEBOL','Lamine Yamal','{}'::text[]),
 ('FUTEBOL','Rodrygo','{}'::text[]),
 ('FUTEBOL','Raphinha','{}'::text[]),
 ('FUTEBOL','Gabriel Jesus','{}'::text[]),
 ('FUTEBOL','Richarlison','{}'::text[]),
 ('FUTEBOL','Casemiro','{}'::text[]),
 ('FUTEBOL','Alisson','{}'::text[]),
 ('FUTEBOL','Thiago Silva','{}'::text[]),
 ('FUTEBOL','Marcelo','{}'::text[]),
 ('FUTEBOL','Endrick','{}'::text[]),
 ('FUTEBOL','Gabigol',array['Gabriel Barbosa']),
 ('FUTEBOL','Hulk','{}'::text[]),
 ('FUTEBOL','Giorgian de Arrascaeta',array['Arrascaeta']),
 ('FUTEBOL','Rogério Ceni','{}'::text[]),
 ('FUTEBOL','Sócrates','{}'::text[]),
 ('FUTEBOL','Adriano Imperador',array['Adriano']),
 ('FUTEBOL','David Beckham','{}'::text[]),
 ('FUTEBOL','Andrés Iniesta','{}'::text[]),
 ('FUTEBOL','Xavi','{}'::text[]),
 ('FUTEBOL','Sergio Ramos','{}'::text[]),
 ('FUTEBOL','Gianluigi Buffon','{}'::text[]),
 ('FUTEBOL','Manuel Neuer','{}'::text[]),
 ('FUTEBOL','Luis Suárez','{}'::text[]),
 ('FUTEBOL','Antoine Griezmann','{}'::text[]),
 ('FUTEBOL','Karim Benzema','{}'::text[]),
 ('FUTEBOL','Wayne Rooney','{}'::text[]),
 ('FUTEBOL','Zlatan Ibrahimović',array['Ibrahimovic']),
 ('NOVELAS','Carminha',array['Carmen Lúcia']),
 ('NOVELAS','Nina','{}'::text[]),
 ('NOVELAS','Tufão','{}'::text[]),
 ('NOVELAS','Nazaré Tedesco',array['Nazaré']),
 ('NOVELAS','Odete Roitman','{}'::text[]),
 ('NOVELAS','Maria de Fátima','{}'::text[]),
 ('NOVELAS','Raquel Accioli','{}'::text[]),
 ('NOVELAS','Félix','{}'::text[]),
 ('NOVELAS','Jade','{}'::text[]),
 ('NOVELAS','Said','{}'::text[]),
 ('NOVELAS','Dona Jura','{}'::text[]),
 ('NOVELAS','Mel','{}'::text[]),
 ('NOVELAS','Bebel','{}'::text[]),
 ('NOVELAS','Perpétua','{}'::text[]),
 ('NOVELAS','Tieta','{}'::text[]),
 ('NOVELAS','Sinhozinho Malta','{}'::text[]),
 ('NOVELAS','Viúva Porcina','{}'::text[]),
 ('NOVELAS','Flora','{}'::text[]),
 ('NOVELAS','Donatela','{}'::text[]),
 ('NOVELAS','Griselda','{}'::text[]),
 ('NOVELAS','Tereza Cristina','{}'::text[]),
 ('NOVELAS','Crô','{}'::text[]),
 ('NOVELAS','Bia Falcão','{}'::text[]),
 ('NOVELAS','Juma Marruá',array['Juma']),
 ('NOVELAS','José Leôncio','{}'::text[]),
 ('NOVELAS','Velho do Rio','{}'::text[]),
 ('NOVELAS','Zeca Diabo','{}'::text[]),
 ('NOVELAS','Odorico Paraguaçu','{}'::text[]),
 ('NOVELAS','Dona Armênia','{}'::text[]),
 ('NOVELAS','Giovanni Improtta','{}'::text[]),
 ('NOVELAS','Isaura','{}'::text[]),
 ('NOVELAS','Maria do Bairro','{}'::text[]),
 ('NOVELAS','Paola Bracho','{}'::text[]),
 ('NOVELAS','Paulina Martins','{}'::text[]),
 ('NOVELAS','Gabriela','{}'::text[]),
 ('NOVELAS','Laura Prudente','{}'::text[]),
 ('CANTORES','Anitta','{}'::text[]),
 ('CANTORES','Ivete Sangalo','{}'::text[]),
 ('CANTORES','Claudia Leitte','{}'::text[]),
 ('CANTORES','Luan Santana','{}'::text[]),
 ('CANTORES','Gusttavo Lima','{}'::text[]),
 ('CANTORES','Marília Mendonça','{}'::text[]),
 ('CANTORES','Jorge e Mateus','{}'::text[]),
 ('CANTORES','Henrique e Juliano','{}'::text[]),
 ('CANTORES','Zé Neto e Cristiano','{}'::text[]),
 ('CANTORES','Maiara e Maraisa','{}'::text[]),
 ('CANTORES','Simone Mendes','{}'::text[]),
 ('CANTORES','Ana Castela','{}'::text[]),
 ('CANTORES','Wesley Safadão','{}'::text[]),
 ('CANTORES','Roberto Carlos','{}'::text[]),
 ('CANTORES','Caetano Veloso','{}'::text[]),
 ('CANTORES','Gilberto Gil','{}'::text[]),
 ('CANTORES','Chico Buarque','{}'::text[]),
 ('CANTORES','Djavan','{}'::text[]),
 ('CANTORES','Rita Lee','{}'::text[]),
 ('CANTORES','Cazuza','{}'::text[]),
 ('CANTORES','Renato Russo','{}'::text[]),
 ('CANTORES','Tim Maia','{}'::text[]),
 ('CANTORES','Elis Regina','{}'::text[]),
 ('CANTORES','Ludmilla','{}'::text[]),
 ('CANTORES','Pabllo Vittar','{}'::text[]),
 ('CANTORES','Gloria Groove','{}'::text[]),
 ('CANTORES','Luísa Sonza','{}'::text[]),
 ('CANTORES','Iza','{}'::text[]),
 ('CANTORES','Alcione','{}'::text[]),
 ('CANTORES','Zeca Pagodinho','{}'::text[]),
 ('CANTORES','Thiaguinho','{}'::text[]),
 ('CANTORES','Péricles','{}'::text[]),
 ('CANTORES','Seu Jorge','{}'::text[]),
 ('CANTORES','Pedro Sampaio','{}'::text[]),
 ('CANTORES','Matuê','{}'::text[]),
 ('CANTORES','Mano Brown','{}'::text[]),
 ('CANTORES','Emicida','{}'::text[]),
 ('CANTORES','Michael Jackson','{}'::text[]),
 ('CANTORES','Madonna','{}'::text[]),
 ('CANTORES','Beyoncé','{}'::text[]),
 ('CANTORES','Taylor Swift','{}'::text[]),
 ('CANTORES','Shakira','{}'::text[]),
 ('CANTORES','Rihanna','{}'::text[]),
 ('CANTORES','Lady Gaga','{}'::text[]),
 ('CANTORES','Bruno Mars','{}'::text[]),
 ('CANTORES','Ed Sheeran','{}'::text[]),
 ('CANTORES','Justin Bieber','{}'::text[]),
 ('CANTORES','Billie Eilish','{}'::text[]),
 ('CANTORES','Dua Lipa','{}'::text[]),
 ('CANTORES','The Weeknd','{}'::text[]),
 ('CANTORES','Elvis Presley','{}'::text[]),
 ('CANTORES','Freddie Mercury','{}'::text[]),
 ('CANTORES','Bad Bunny','{}'::text[]),
 ('ANIME','Goku',array['Son Goku']),
 ('ANIME','Vegeta','{}'::text[]),
 ('ANIME','Gohan','{}'::text[]),
 ('ANIME','Piccolo','{}'::text[]),
 ('ANIME','Naruto',array['Naruto Uzumaki']),
 ('ANIME','Sasuke',array['Sasuke Uchiha']),
 ('ANIME','Kakashi',array['Kakashi Hatake']),
 ('ANIME','Sakura Haruno','{}'::text[]),
 ('ANIME','Itachi',array['Itachi Uchiha']),
 ('ANIME','Luffy',array['Monkey D. Luffy']),
 ('ANIME','Zoro',array['Roronoa Zoro']),
 ('ANIME','Nami','{}'::text[]),
 ('ANIME','Sanji','{}'::text[]),
 ('ANIME','Ichigo Kurosaki','{}'::text[]),
 ('ANIME','Light Yagami',array['Kira']),
 ('ANIME','L','{}'::text[]),
 ('ANIME','Eren Yeager',array['Eren Jaeger']),
 ('ANIME','Mikasa Ackerman',array['Mikasa']),
 ('ANIME','Levi Ackerman',array['Levi']),
 ('ANIME','Tanjiro Kamado',array['Tanjiro']),
 ('ANIME','Nezuko Kamado',array['Nezuko']),
 ('ANIME','Pikachu','{}'::text[]),
 ('ANIME','Ash Ketchum',array['Ash']),
 ('ANIME','Seiya',array['Seiya de Pégaso']),
 ('ANIME','Shiryu','{}'::text[]),
 ('ANIME','Ikki','{}'::text[]),
 ('ANIME','Yusuke Urameshi','{}'::text[]),
 ('ANIME','Edward Elric','{}'::text[]),
 ('ANIME','Saitama','{}'::text[]),
 ('ANIME','Gon Freecss',array['Gon']),
 ('ANIME','Killua',array['Killua Zoldyck']),
 ('ANIME','Izuku Midoriya',array['Deku']),
 ('ANIME','All Might','{}'::text[]),
 ('ANIME','Satoru Gojo',array['Gojo']),
 ('ANIME','Yuji Itadori','{}'::text[]),
 ('ANIME','Sailor Moon','{}'::text[]),
 ('ANIME','Doraemon','{}'::text[]),
 ('ANIME','Totoro','{}'::text[]),
 ('ANIME','Kenshin Himura',array['Kenshin']),
 ('ANIME','Spike Spiegel','{}'::text[]),
 ('ANIME','Ryuk','{}'::text[]),
 ('YOUTUBERS','Felipe Neto','{}'::text[]),
 ('YOUTUBERS','Luccas Neto','{}'::text[]),
 ('YOUTUBERS','Whindersson Nunes',array['Whindersson']),
 ('YOUTUBERS','Casimiro',array['Casimiro Miguel']),
 ('YOUTUBERS','Gaules','{}'::text[]),
 ('YOUTUBERS','Enaldinho','{}'::text[]),
 ('YOUTUBERS','Rezendeevil',array['Rezende']),
 ('YOUTUBERS','AuthenticGames',array['Authentic Games']),
 ('YOUTUBERS','Cellbit','{}'::text[]),
 ('YOUTUBERS','Felipe Castanhari',array['Castanhari']),
 ('YOUTUBERS','Júlio Cocielo',array['Cocielo']),
 ('YOUTUBERS','Kéfera','{}'::text[]),
 ('YOUTUBERS','Camila Loures','{}'::text[]),
 ('YOUTUBERS','Lucas Inutilismo','{}'::text[]),
 ('YOUTUBERS','Iberê Thenório',array['Manual do Mundo']),
 ('YOUTUBERS','Jout Jout','{}'::text[]),
 ('YOUTUBERS','Bianca Andrade',array['Boca Rosa']),
 ('YOUTUBERS','Nilce Moretto','{}'::text[]),
 ('YOUTUBERS','Leon Martins',array['Leon']),
 ('YOUTUBERS','T3ddy','{}'::text[]),
 ('YOUTUBERS','Paulinho o Loko','{}'::text[]),
 ('YOUTUBERS','Alanzoka','{}'::text[]),
 ('YOUTUBERS','Nobru','{}'::text[]),
 ('YOUTUBERS','Virginia Fonseca',array['Virginia']),
 ('YOUTUBERS','MrBeast',array['Mr Beast']),
 ('YOUTUBERS','PewDiePie','{}'::text[]),
 ('YOUTUBERS','Mark Rober','{}'::text[]),
 ('SÉRIES','Walter White',array['Heisenberg']),
 ('SÉRIES','Jesse Pinkman','{}'::text[]),
 ('SÉRIES','Saul Goodman','{}'::text[]),
 ('SÉRIES','Eleven',array['Onze']),
 ('SÉRIES','Jon Snow','{}'::text[]),
 ('SÉRIES','Daenerys Targaryen',array['Daenerys']),
 ('SÉRIES','Tyrion Lannister',array['Tyrion']),
 ('SÉRIES','Sheldon Cooper',array['Sheldon']),
 ('SÉRIES','Penny','{}'::text[]),
 ('SÉRIES','Ross Geller',array['Ross']),
 ('SÉRIES','Rachel Green',array['Rachel']),
 ('SÉRIES','Joey Tribbiani',array['Joey']),
 ('SÉRIES','Chandler Bing',array['Chandler']),
 ('SÉRIES','Michael Scott','{}'::text[]),
 ('SÉRIES','Dwight Schrute','{}'::text[]),
 ('SÉRIES','Wandinha Addams',array['Wandinha']),
 ('SÉRIES','Professor',array['O Professor']),
 ('SÉRIES','Tóquio','{}'::text[]),
 ('SÉRIES','Berlim','{}'::text[]),
 ('SÉRIES','Seong Gi-hun',array['Gi-hun']),
 ('SÉRIES','Dexter Morgan','{}'::text[]),
 ('SÉRIES','Gregory House',array['Dr. House']),
 ('SÉRIES','Meredith Grey','{}'::text[]),
 ('SÉRIES','Rick Grimes','{}'::text[]),
 ('SÉRIES','Daryl Dixon','{}'::text[]),
 ('SÉRIES','Thomas Shelby',array['Tommy Shelby']),
 ('SÉRIES','Tony Soprano','{}'::text[]),
 ('SÉRIES','Homelander',array['Capitão Pátria']),
 ('SÉRIES','Chaves','{}'::text[]),
 ('SÉRIES','Seu Madruga','{}'::text[]),
 ('SÉRIES','Chiquinha','{}'::text[]),
 ('SÉRIES','Quico','{}'::text[]),
 ('SÉRIES','Professor Girafales',array['Girafales']),
 ('SÉRIES','Dona Florinda','{}'::text[]),
 ('SÉRIES','Seu Barriga','{}'::text[]),
 ('SÉRIES','Mr. Bean','{}'::text[]),
 ('SÉRIES','Steve Urkel',array['Urkel']),
 ('SÉRIES','Chris Rock',array['Chris']),
 ('DESENHOS','Bob Esponja','{}'::text[]),
 ('DESENHOS','Patrick Estrela','{}'::text[]),
 ('DESENHOS','Lula Molusco','{}'::text[]),
 ('DESENHOS','Seu Sirigueijo','{}'::text[]),
 ('DESENHOS','Mickey Mouse',array['Mickey']),
 ('DESENHOS','Minnie','{}'::text[]),
 ('DESENHOS','Pato Donald',array['Donald']),
 ('DESENHOS','Pateta','{}'::text[]),
 ('DESENHOS','Pernalonga','{}'::text[]),
 ('DESENHOS','Patolino','{}'::text[]),
 ('DESENHOS','Piu-Piu','{}'::text[]),
 ('DESENHOS','Frajola','{}'::text[]),
 ('DESENHOS','Scooby-Doo','{}'::text[]),
 ('DESENHOS','Salsicha','{}'::text[]),
 ('DESENHOS','Tom','{}'::text[]),
 ('DESENHOS','Jerry','{}'::text[]),
 ('DESENHOS','Homer Simpson',array['Homer']),
 ('DESENHOS','Bart Simpson',array['Bart']),
 ('DESENHOS','Lisa Simpson',array['Lisa']),
 ('DESENHOS','Marge Simpson',array['Marge']),
 ('DESENHOS','Peter Griffin','{}'::text[]),
 ('DESENHOS','Pica-Pau','{}'::text[]),
 ('DESENHOS','Popeye','{}'::text[]),
 ('DESENHOS','Shrek','{}'::text[]),
 ('DESENHOS','Buzz Lightyear',array['Buzz']),
 ('DESENHOS','Woody','{}'::text[]),
 ('DESENHOS','Relâmpago McQueen',array['McQueen']),
 ('DESENHOS','Elsa','{}'::text[]),
 ('DESENHOS','Olaf','{}'::text[]),
 ('DESENHOS','Simba','{}'::text[]),
 ('DESENHOS','Mônica','{}'::text[]),
 ('DESENHOS','Cebolinha','{}'::text[]),
 ('DESENHOS','Cascão','{}'::text[]),
 ('DESENHOS','Magali','{}'::text[]),
 ('DESENHOS','Chico Bento','{}'::text[]),
 ('DESENHOS','Ben Tennyson',array['Ben 10']),
 ('DESENHOS','Timmy Turner','{}'::text[]),
 ('DESENHOS','Dexter','{}'::text[]),
 ('DESENHOS','Johnny Bravo','{}'::text[]),
 ('DESENHOS','Coragem',array['Coragem o Cão Covarde']),
 ('DESENHOS','Finn','{}'::text[]),
 ('DESENHOS','Jake','{}'::text[]),
 ('DESENHOS','Gumball','{}'::text[]),
 ('DESENHOS','Mordecai','{}'::text[]),
 ('DESENHOS','Rigby','{}'::text[]),
 ('DESENHOS','Phineas','{}'::text[]),
 ('DESENHOS','Ferb','{}'::text[]),
 ('DESENHOS','Perry o Ornitorrinco',array['Perry']),
 ('DESENHOS','Peppa Pig',array['Peppa']),
 ('FAMOSOS','Xuxa','{}'::text[]),
 ('FAMOSOS','Faustão','{}'::text[]),
 ('FAMOSOS','Silvio Santos','{}'::text[]),
 ('FAMOSOS','Luciano Huck','{}'::text[]),
 ('FAMOSOS','Ana Maria Braga','{}'::text[]),
 ('FAMOSOS','Fátima Bernardes','{}'::text[]),
 ('FAMOSOS','William Bonner','{}'::text[]),
 ('FAMOSOS','Tiago Leifert','{}'::text[]),
 ('FAMOSOS','Angélica','{}'::text[]),
 ('FAMOSOS','Eliana','{}'::text[]),
 ('FAMOSOS','Gugu Liberato',array['Gugu']),
 ('FAMOSOS','Jô Soares','{}'::text[]),
 ('FAMOSOS','Ratinho','{}'::text[]),
 ('FAMOSOS','José Luiz Datena',array['Datena']),
 ('FAMOSOS','Marcos Mion','{}'::text[]),
 ('FAMOSOS','Tatá Werneck','{}'::text[]),
 ('FAMOSOS','Paulo Gustavo','{}'::text[]),
 ('FAMOSOS','Fábio Porchat','{}'::text[]),
 ('FAMOSOS','Juliette','{}'::text[]),
 ('FAMOSOS','Gil do Vigor','{}'::text[]),
 ('FAMOSOS','Bruna Marquezine','{}'::text[]),
 ('FAMOSOS','Gisele Bündchen','{}'::text[]),
 ('FAMOSOS','Rodrigo Santoro','{}'::text[]),
 ('FAMOSOS','Wagner Moura','{}'::text[]),
 ('FAMOSOS','Fernanda Montenegro','{}'::text[]),
 ('FAMOSOS','Selton Mello','{}'::text[]),
 ('FAMOSOS','Lázaro Ramos','{}'::text[]),
 ('FAMOSOS','Taís Araújo','{}'::text[]),
 ('FAMOSOS','Elon Musk','{}'::text[]),
 ('FAMOSOS','Bill Gates','{}'::text[]),
 ('FAMOSOS','Steve Jobs','{}'::text[]),
 ('FAMOSOS','Mark Zuckerberg','{}'::text[]),
 ('FAMOSOS','Oprah Winfrey','{}'::text[]),
 ('FAMOSOS','Kim Kardashian','{}'::text[]),
 ('FAMOSOS','Barack Obama','{}'::text[]),
 ('FAMOSOS','Albert Einstein',array['Einstein']),
 ('FAMOSOS','Leonardo da Vinci','{}'::text[]),
 ('FAMOSOS','Isaac Newton','{}'::text[]),
 ('FAMOSOS','Napoleão Bonaparte',array['Napoleão']),
 ('FAMOSOS','Dom Pedro I','{}'::text[]),
 ('FAMOSOS','Santos Dumont','{}'::text[]),
 ('FAMOSOS','Tiradentes','{}'::text[])
on conflict(theme,name) do update set aliases=excluded.aliases,active=true;
